// Code generated by MockGen. DO NOT EDIT.
// Source: ingestor_processor.go
//
// Generated by this command:
//
//	mockgen -source=ingestor_processor.go -destination=../utilstest/mocksgen/log/mocked_ingestor_processor.go
//

// Package mock_log is a generated GoMock package.
package mock_log
