// Code generated by MockGen. DO NOT EDIT.
// Source: message_poller.go
//
// Generated by this command:
//
//	mockgen -source=message_poller.go -destination=../utilstest/mocksgen/log/mocked_message_poller.go
//

// Package mock_log is a generated GoMock package.
package mock_log
