// Code generated by MockGen. DO NOT EDIT.
// Source: event_transformer.go
//
// Generated by this command:
//
//	mockgen -source=event_transformer.go -destination=../utilstest/mocksgen/log/mocked_event_transformer.go
//

// Package mock_log is a generated GoMock package.
package mock_log
