// Code generated by MockGen. DO NOT EDIT.
// Source: kafka.go
//
// Generated by this command:
//
//	mockgen -source=kafka.go -destination=../internal/utilstest/mocksgen/mocked_kafka.go
//

// Package mock_internal is a generated GoMock package.
package mock_internal
