// Code generated by MockGen. DO NOT EDIT.
// Source: error.go
//
// Generated by this command:
//
//	mockgen -source=error.go -destination=../utilstest/mocksgen/ingestor/mocked_error.go
//

// Package mock_ingestor is a generated GoMock package.
package mock_ingestor
