// Code generated by MockGen. DO NOT EDIT.
// Source: ingestor.go
//
// Generated by this command:
//
//	mockgen -source=ingestor.go -destination=../utilstest/mocksgen/ingestor/mocked_ingestor.go
//

// Package mock_ingestor is a generated GoMock package.
package mock_ingestor

import (
	context "context"
	reflect "reflect"
	ingestor "synapsePlatform/internal/ingestor"

	gomock "go.uber.org/mock/gomock"
)

// MockDataProcessor is a mock of DataProcessor interface.
type MockDataProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockDataProcessorMockRecorder
	isgomock struct{}
}

// MockDataProcessorMockRecorder is the mock recorder for MockDataProcessor.
type MockDataProcessorMockRecorder struct {
	mock *MockDataProcessor
}

// NewMockDataProcessor creates a new mock instance.
func NewMockDataProcessor(ctrl *gomock.Controller) *MockDataProcessor {
	mock := &MockDataProcessor{ctrl: ctrl}
	mock.recorder = &MockDataProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataProcessor) EXPECT() *MockDataProcessorMockRecorder {
	return m.recorder
}

// ProcessData mocks base method.
func (m *MockDataProcessor) ProcessData(ctx context.Context) (*ingestor.DeviceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessData", ctx)
	ret0, _ := ret[0].(*ingestor.DeviceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessData indicates an expected call of ProcessData.
func (mr *MockDataProcessorMockRecorder) ProcessData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessData", reflect.TypeOf((*MockDataProcessor)(nil).ProcessData), ctx)
}

// MockMessageStorer is a mock of MessageStorer interface.
type MockMessageStorer struct {
	ctrl     *gomock.Controller
	recorder *MockMessageStorerMockRecorder
	isgomock struct{}
}

// MockMessageStorerMockRecorder is the mock recorder for MockMessageStorer.
type MockMessageStorerMockRecorder struct {
	mock *MockMessageStorer
}

// NewMockMessageStorer creates a new mock instance.
func NewMockMessageStorer(ctrl *gomock.Controller) *MockMessageStorer {
	mock := &MockMessageStorer{ctrl: ctrl}
	mock.recorder = &MockMessageStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageStorer) EXPECT() *MockMessageStorerMockRecorder {
	return m.recorder
}

// StoreData mocks base method.
func (m *MockMessageStorer) StoreData(ctx context.Context, data *ingestor.BaseEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreData", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreData indicates an expected call of StoreData.
func (mr *MockMessageStorerMockRecorder) StoreData(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreData", reflect.TypeOf((*MockMessageStorer)(nil).StoreData), ctx, data)
}

// MockTransformer is a mock of Transformer interface.
type MockTransformer struct {
	ctrl     *gomock.Controller
	recorder *MockTransformerMockRecorder
	isgomock struct{}
}

// MockTransformerMockRecorder is the mock recorder for MockTransformer.
type MockTransformerMockRecorder struct {
	mock *MockTransformer
}

// NewMockTransformer creates a new mock instance.
func NewMockTransformer(ctrl *gomock.Controller) *MockTransformer {
	mock := &MockTransformer{ctrl: ctrl}
	mock.recorder = &MockTransformerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransformer) EXPECT() *MockTransformerMockRecorder {
	return m.recorder
}

// Transform mocks base method.
func (m *MockTransformer) Transform(ctx context.Context, msg *ingestor.DeviceMessage) (*ingestor.BaseEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transform", ctx, msg)
	ret0, _ := ret[0].(*ingestor.BaseEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transform indicates an expected call of Transform.
func (mr *MockTransformerMockRecorder) Transform(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transform", reflect.TypeOf((*MockTransformer)(nil).Transform), ctx, msg)
}

// MockNormalizedData is a mock of NormalizedData interface.
type MockNormalizedData struct {
	ctrl     *gomock.Controller
	recorder *MockNormalizedDataMockRecorder
	isgomock struct{}
}

// MockNormalizedDataMockRecorder is the mock recorder for MockNormalizedData.
type MockNormalizedDataMockRecorder struct {
	mock *MockNormalizedData
}

// NewMockNormalizedData creates a new mock instance.
func NewMockNormalizedData(ctrl *gomock.Controller) *MockNormalizedData {
	mock := &MockNormalizedData{ctrl: ctrl}
	mock.recorder = &MockNormalizedDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNormalizedData) EXPECT() *MockNormalizedDataMockRecorder {
	return m.recorder
}

// Normalize mocks base method.
func (m *MockNormalizedData) Normalize() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Normalize")
	ret0, _ := ret[0].(error)
	return ret0
}

// Normalize indicates an expected call of Normalize.
func (mr *MockNormalizedDataMockRecorder) Normalize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Normalize", reflect.TypeOf((*MockNormalizedData)(nil).Normalize))
}

// Validate mocks base method.
func (m *MockNormalizedData) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockNormalizedDataMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockNormalizedData)(nil).Validate))
}
