// Code generated by MockGen. DO NOT EDIT.
// Source: processor.go
//
// Generated by this command:
//
//	mockgen -source=processor.go -destination=../utilstest/mocksgen/ingestor/mocked_processor.go
//

// Package mock_ingestor is a generated GoMock package.
package mock_ingestor

import (
	context "context"
	reflect "reflect"
	ingestor "synapsePlatform/internal/ingestor"

	gomock "go.uber.org/mock/gomock"
)

// MockMessagePoller is a mock of MessagePoller interface.
type MockMessagePoller struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePollerMockRecorder
	isgomock struct{}
}

// MockMessagePollerMockRecorder is the mock recorder for MockMessagePoller.
type MockMessagePollerMockRecorder struct {
	mock *MockMessagePoller
}

// NewMockMessagePoller creates a new mock instance.
func NewMockMessagePoller(ctrl *gomock.Controller) *MockMessagePoller {
	mock := &MockMessagePoller{ctrl: ctrl}
	mock.recorder = &MockMessagePollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePoller) EXPECT() *MockMessagePollerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMessagePoller) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMessagePollerMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMessagePoller)(nil).Close), ctx)
}

// PollMessage mocks base method.
func (m *MockMessagePoller) PollMessage(ctx context.Context) (*ingestor.DeviceMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PollMessage", ctx)
	ret0, _ := ret[0].(*ingestor.DeviceMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PollMessage indicates an expected call of PollMessage.
func (mr *MockMessagePollerMockRecorder) PollMessage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PollMessage", reflect.TypeOf((*MockMessagePoller)(nil).PollMessage), ctx)
}

// Subscribe mocks base method.
func (m *MockMessagePoller) Subscribe(ctx context.Context, topics string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, topics)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockMessagePollerMockRecorder) Subscribe(ctx, topics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockMessagePoller)(nil).Subscribe), ctx, topics)
}
