// Code generated by MockGen. DO NOT EDIT.
// Source: transformer.go
//
// Generated by this command:
//
//	mockgen -source=transformer.go -destination=../utilstest/mocksgen/ingestor/mocked_transformer.go
//

// Package mock_ingestor is a generated GoMock package.
package mock_ingestor
