// Code generated by MockGen. DO NOT EDIT.
// Source: sqllite.go
//
// Generated by this command:
//
//	mockgen -source=sqllite.go -destination=../utilstest/mocksgen/sqllite/mocked_sqllite.go
//

// Package mock_sqllite is a generated GoMock package.
package mock_sqllite
