//go:generate mockgen -source=$GOFILE -destination=../../utilstest/mocksgen/summary/mocked_$GOFILE
package summary

import (
	"context"
	"fmt"
	"strings"
	"time"

	"synapsePlatform/internal/api"
	"synapsePlatform/internal/intelligence/provider"
)

// Completer is the small completion capability the summary service consumes.
// Declared here, where it is used, so the summary package does not depend on a
// broad exported provider interface. The concrete provider router satisfies
// this without being imported here.
type Completer interface {
	Complete(ctx context.Context, req provider.CompletionRequest) (*provider.CompletionResponse, error)
}

type Service struct {
	reader         api.AggregateReader
	evidenceReader SummaryEvidenceReader
	completer      Completer
	providerName   string
	model          string
	maxTokens      int
	temperature    float64
	promptVersion  string
	cacheMetrics   CacheMetrics
}

// New builds a summary service backed by the given completion capability.
//
// providerName is the name of the default provider the service routes to; it
// becomes part of the cache key so summaries generated by different providers
// are not confused. model, maxTokens, and temperature are passed through to
// the provider on each completion and are also cache-key dimensions.
// promptVersion is recorded alongside summaries so the cache key and persisted
// output stay comparable across prompt changes.
//
// Optional behavior (cache metrics) can be configured via ServiceOption
// functions, e.g. summary.WithCacheMetrics(recorder).
func New(reader api.AggregateReader, completer Completer, providerName, model string, maxTokens int, temperature float64, opts ...ServiceOption) *Service {
	s := &Service{
		reader:         reader,
		evidenceReader: noopEvidenceReader{},
		completer:      completer,
		providerName:   providerName,
		model:          model,
		maxTokens:      maxTokens,
		temperature:    temperature,
		promptVersion:  SummaryPromptVersion,
		cacheMetrics:   noopCacheMetrics{},
	}
	for _, opt := range opts {
		opt(s)
	}
	return s
}

func (s *Service) Summarize(ctx context.Context, req api.Request) (*api.Report, error) {
	stats, err := s.reader.AggregateByDomain(ctx, req.Since)
	if err != nil {
		return nil, fmt.Errorf("aggregate events: %w", err)
	}

	var domainStats []api.DomainStat
	for _, st := range stats {
		if req.Domain == "" || st.Domain == req.Domain {
			domainStats = append(domainStats, st)
		}
	}

	cacheKey := BuildCacheKey(
		req.Domain, req.Since,
		s.providerName, s.model, s.promptVersion,
		s.temperature, s.maxTokens,
		domainStats,
	)

	cached, ok, err := s.reader.LatestSummary(ctx, api.SummaryLookup{
		Domain:        cacheKey.Domain,
		WindowFrom:    cacheKey.WindowFrom,
		Provider:      cacheKey.Provider,
		Model:         cacheKey.Model,
		PromptVersion: cacheKey.PromptVersion,
		Temperature:   cacheKey.Temperature,
		MaxTokens:     cacheKey.MaxTokens,
		InputHash:     cacheKey.InputHash,
	})
	if err != nil {
		return nil, fmt.Errorf("check summary cache: %w", err)
	}
	if ok {
		s.cacheMetrics.CacheHit(ctx, req.Domain)
		return cached, nil
	}
	s.cacheMetrics.CacheMiss(ctx, req.Domain)

	if len(domainStats) == 0 {
		report := &api.Report{
			Domain:        req.Domain,
			WindowFrom:    req.Since,
			Model:         s.model,
			Content:       "No events found for the requested period.",
			Provider:      s.providerName,
			PromptVersion: s.promptVersion,
			InputHash:     cacheKey.InputHash,
			CreatedAt:     time.Now().UTC(),
		}
		if _, err := s.reader.SaveSummary(ctx, report); err != nil {
			return report, fmt.Errorf("save summary: %w", err)
		}
		return report, nil
	}

	// Load a bounded, curated evidence set for the requested domain/window.
	// The model can only cite event IDs it received as evidence, so this is
	// what makes summaries evidence-backed rather than hallucinated. The
	// evidence reader returns stable event fields only (event_id, domain,
	// event_type, entity_id, occurred_at) — no raw payloads or secrets.
	evidence, err := s.evidenceReader.ListSummaryEvidence(ctx, api.EvidenceRequest{
		Domain:     req.Domain,
		Since:      req.Since,
		MaxResults: api.DefaultMaxEvidenceEvents,
	})
	if err != nil {
		return nil, fmt.Errorf("load summary evidence: %w", err)
	}

	prompt := BuildSummaryPrompt(req.Domain, domainStats, evidence)

	resp, err := s.completer.Complete(ctx, provider.CompletionRequest{
		Model:       s.model,
		Prompt:      prompt,
		MaxTokens:   s.maxTokens,
		Temperature: s.temperature,
		Metadata: map[string]string{
			"purpose":        "summary",
			"prompt_version": s.promptVersion,
			"domain":         req.Domain,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("llm completion: %w", err)
	}

	model := resp.Model
	if model == "" {
		model = s.model
	}
	providerName := resp.Provider
	if providerName == "" {
		providerName = s.providerName
	}

	report := &api.Report{
		Domain:        req.Domain,
		WindowFrom:    req.Since,
		Model:         model,
		Content:       strings.TrimSpace(resp.Content),
		Provider:      providerName,
		PromptVersion: s.promptVersion,
		InputHash:     cacheKey.InputHash,
		CreatedAt:     time.Now().UTC(),
	}

	summaryID, err := s.reader.SaveSummary(ctx, report)
	if err != nil {
		return report, fmt.Errorf("save summary: %w", err)
	}

	// Persist the evidence links so the API can show why the summary said
	// what it said. Every event in the evidence set is linked with the
	// "evidence" relationship.
	if len(evidence) > 0 {
		links := make([]api.SummaryEvidenceLink, len(evidence))
		for i, e := range evidence {
			links[i] = api.SummaryEvidenceLink{
				SummaryID:    summaryID,
				EventID:      e.EventID,
				Relationship: api.EvidenceRelationshipEvidence,
			}
		}
		if err := s.reader.SaveSummaryEvidenceLinks(ctx, links); err != nil {
			return report, fmt.Errorf("save summary evidence links: %w", err)
		}
	}

	return report, nil
}
